# Generated by Django 3.2.9 on 2022-05-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_auth',
            field=models.BooleanField(default=False),
        ),
    ]
